//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum ___VARIABLE_moduleName___ {
    
    struct ViewOutput {
    }

    struct ViewInput {
    }

    enum NavigationOption {
    }
}

protocol ___VARIABLE_moduleName___WireframeInterface: WireframeInterface {
    func navigate(using option: Driver<___VARIABLE_moduleName___.NavigationOption>)
    func navigate(to option: ___VARIABLE_moduleName___.NavigationOption)
}

protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
    func setupBinding(with output: ___VARIABLE_moduleName___.ViewOutput) -> ___VARIABLE_moduleName___.ViewInput
}

protocol ___VARIABLE_moduleName___InteractorInterface: InteractorInterface {
}
